### ISSUE TITLE
Druhá Instance služby castleservice

### ISSUE THREAD

**Issue by raven2cz** [macalak/javadays2016#1]
Dobrý den,
na prezentaci jste ukazoval spuštění dvou instancí microservice castleservice. Snažím se to tu nastavit, ale configservice mě nenechá změnit port, lokální úprava server.port u service nepomůže, protože remote konfigurace ji vždy nahradí. 
Jak jste to dokázal změnit? :-)
Díky za radu.
Fischer

**Comment by macalak** [comment]
Dobry den,

pouzite ENV premennu PORT pri starte sluzby.

napr.   java -DPORT=9090 -jar castleservice.jar

S pozdravom,

Macalak.



Dňa 02.12.2016 o 13:43 Tonda Fischer napísal(a):

**Comment by raven2cz** [comment]
Díky, funguje.
